language: node_js
node_js:
- '0.10'
deploy:
  provider: heroku
  api_key:
    secure: NPpbcrvYTt1bqY7w0W4A7tULbAHeusCmtbmqWuvIzr0cfSJAu2bO0CZzabfAgpoOftTFdH1RDeX47zdw5O7ITJhaq0MadrlOUwSllG13jcHBsJgJ3ss1yFcxPTn+pqkSC3VPbMJVP9U65PKuyriwTg2n45mb42xUhZyNPsX7lCs=
  app: yomergency
  on:
    repo: charlierproctor/yomergency
